param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent)
)

$ErrorActionPreference = 'Stop'

function Read-Table($text, $name) {
    $match = [regex]::Match($text, '(?s)' + [regex]::Escape($name) + '\s*=\s*\{(.*?)\r?\n\}')
    if (-not $match.Success) { throw "Missing table: $name" }
    return $match.Groups[1].Value
}

function Read-Braces($text, $start) {
    $depth = 0
    for ($i = $start; $i -lt $text.Length; $i++) {
        if ($text[$i] -eq '{') { $depth++ }
        if ($text[$i] -eq '}') {
            $depth--
            if ($depth -eq 0) { return $text.Substring($start, $i - $start + 1) }
        }
    }
    throw "Unclosed table at position $start"
}

$uiText = [IO.File]::ReadAllText((Join-Path $Root 'Questie-335\Compat\UiMapData.lua'))
$zoneText = [IO.File]::ReadAllText((Join-Path $Root 'Questie-335_AzerothCore\Database\Zones\zoneTables.lua'))
$instanceMaps = @{}
$instanceUiIds = @{}
foreach ($match in [regex]::Matches((Read-Table $uiText 'local wdmInstanceMapData'), '(?m)^\s*\[(\d+)\]\s*=\s*\{[^\r\n]*wdmInstanceMap = true[^\r\n]*-- area (\d+)')) {
    $uiId = [int]$match.Groups[1].Value
    $instanceMaps[$uiId] = [int]$match.Groups[2].Value
    $instanceUiIds[$uiId] = $true
}
if ($instanceMaps.Count -lt 100) { throw "Incomplete WDM instance maps" }

$zoneIds = @{}
foreach ($match in [regex]::Matches((Read-Table $zoneText 'ZoneDB.private.zoneIDs'), '(?m)^\s*([A-Z][A-Z0-9_]+)\s*=\s*(\d+)')) {
    $zoneIds[$match.Groups[1].Value] = [int]$match.Groups[2].Value
}
$areaToUi = @{}
foreach ($match in [regex]::Matches((Read-Table $zoneText 'ZoneDB.private.areaIdToUiMapId'), '(?m)^\s*\[(\d+)\]\s*=\s*(\d+)')) {
    $areaToUi[[int]$match.Groups[1].Value] = [int]$match.Groups[2].Value
}
foreach ($match in [regex]::Matches((Read-Table $zoneText 'ZoneDB.private.specialZoneIdToUiMapId'), '(?m)^\s*\[(\d+)\]\s*=\s*(\d+)')) {
    $areaToUi[[int]$match.Groups[1].Value] = [int]$match.Groups[2].Value
}
foreach ($uiId in $instanceMaps.Keys) {
    if ($uiId -ge 11000 -or ($uiId -lt 1000 -and $areaToUi[$instanceMaps[$uiId]] -ne $uiId)) {
        $areaToUi[11000 + $uiId] = $uiId
    }
}

$output = @(
    '-- Generated by tools/generate_legacy_wdm_spawns.ps1 from AzerothCore corrections.'
    '-- Only NPCs/objects with missing Legacy instance positions are included.'
    'local data = QuestieLoader:CreateModule("LegacyWDMSpawns")'
)

foreach ($kind in @('npc', 'object')) {
    $legacyText = [IO.File]::ReadAllText((Join-Path $Root "Questie-335_Legacy\Database\Wotlk\wotlk$($kind.Substring(0,1).ToUpper() + $kind.Substring(1))DB.lua"))
    $acoreText = [IO.File]::ReadAllText((Join-Path $Root "Questie-335_AzerothCore\Compat\AzerothCore$($kind.Substring(0,1).ToUpper() + $kind.Substring(1))Corrections.lua"))
    $missing = @{}
    foreach ($record in [regex]::Matches($legacyText, '(?m)^\[(\d+)\]\s*=\s*\{[^\r\n]*')) {
        $placeholderZones = @{}
        foreach ($placeholder in [regex]::Matches($record.Value, '\[(\d+)\]\s*=\s*\{\{-1,-1\}')) {
            $placeholderZones[[int]$placeholder.Groups[1].Value] = $true
        }
        if ($placeholderZones.Count) { $missing[[int]$record.Groups[1].Value] = $placeholderZones }
    }
    $entries = @{}
    foreach ($block in [regex]::Matches($acoreText, '(?ms)^        \[(\d+)\]\s*=\s*\{(.*?)^        \},')) {
        $id = [int]$block.Groups[1].Value
        if (-not $missing.ContainsKey($id)) { continue }
        $spawnMatch = [regex]::Match($block.Groups[2].Value, '\[' + $kind + 'Keys\.spawns\]\s*=\s*\{')
        if (-not $spawnMatch.Success) { continue }
        $spawns = Read-Braces $block.Groups[2].Value ($spawnMatch.Index + $spawnMatch.Length - 1)
        $byInstance = @{}
        foreach ($zoneMatch in [regex]::Matches($spawns, '\[zoneIDs\.([A-Z0-9_]+)\]\s*=\s*\{')) {
            $zoneId = $zoneIds[$zoneMatch.Groups[1].Value]
            if (-not $zoneId) { continue }
            $uiId = $areaToUi[$zoneId]
            if (-not $instanceUiIds[$uiId]) { continue }
            $baseZoneId = $instanceMaps[$uiId]
            if (-not $missing[$id][$baseZoneId]) { continue }
            $position = $zoneMatch.Index + $zoneMatch.Length - 1
            $coords = Read-Braces $spawns $position
            $coords = $coords -replace '\{-1,-1\},', ''
            if ($coords -eq '{{-1,-1}}') { continue }
            if (-not $byInstance.ContainsKey($baseZoneId)) { $byInstance[$baseZoneId] = @{} }
            $byInstance[$baseZoneId][$zoneId] = $coords
        }
        if ($byInstance.Count) { $entries[$id] = $byInstance }
    }
    $output += "data.$kind = {"
    foreach ($id in ($entries.Keys | Sort-Object)) {
        $instances = @()
        foreach ($base in ($entries[$id].Keys | Sort-Object)) {
            $zones = @()
            foreach ($zoneId in ($entries[$id][$base].Keys | Sort-Object)) {
                $zones += "[$zoneId]=$($entries[$id][$base][$zoneId])"
            }
            $instances += "[$base]={$($zones -join ',')}"
        }
        $output += "    [$id]={$($instances -join ',')},"
    }
    $output += '}'
    Write-Output "$kind records: $($entries.Count)"
}

$target = Join-Path $Root 'Questie-335_Legacy\Database\LegacyWDMSpawns.lua'
[IO.File]::WriteAllText($target, ($output -join "`n") + "`n", (New-Object Text.UTF8Encoding($false)))
