--! This file is automatically generated. Do not modify.
-- Generated by tools/generate_acore_reputation_rates.py from AzerothCore
-- reputation_reward_rate base, update, and module SQL.

-- factionId = {quest, daily, weekly, monthly, repeatable}
QuestieCompat.AzerothCoreReputationRates = {
    [529] = {1, 1, 1, 1, 1},
    [576] = {4, 4, 1, 1, 4},
    [609] = {1, 1, 1, 1, 1},
    [941] = {1, 1, 1, 1, 1},
    [970] = {1, 1, 1, 1, 1},
    [978] = {1, 1, 1, 1, 1},
    [1037] = {1, 1, 1, 1, 1},
    [1052] = {1, 1, 1, 1, 1},
    [1073] = {1, 2, 1, 1, 1},
    [1090] = {1.3, 1.3, 1.3, 1.3, 1.3},
    [1091] = {1.3, 1.3, 1.3, 1.3, 1.3},
    [1098] = {1.3, 1.3, 1.3, 1.3, 1.3},
    [1104] = {1, 2, 1, 1, 1},
    [1105] = {1, 2, 1, 1, 1},
    [1106] = {1.3, 1.3, 1.3, 1.3, 1.3},
    [1119] = {1.3, 1.3, 1.3, 1.3, 1.3},
}
