import argparse
import sys
from decimal import Decimal, InvalidOperation
from pathlib import Path


sys.dont_write_bytecode = True
TOOLS_DIR = Path(__file__).resolve().parent
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

from validate_acore_quest_metadata import load_acore_sql_table  # noqa: E402


DEFAULT_OUTPUT = Path("Questie-335_AzerothCore/Compat/AzerothCoreReputationRates.lua")
QUEST_RATE_COLUMNS = (
    "quest_rate",
    "quest_daily_rate",
    "quest_weekly_rate",
    "quest_monthly_rate",
    "quest_repeatable_rate",
)
ALL_RATE_COLUMNS = (*QUEST_RATE_COLUMNS, "creature_rate", "spell_rate")


def parse_faction_id(value):
    try:
        faction_id = int(value)
    except (TypeError, ValueError) as error:
        raise ValueError(f"faction must be an integer, got {value!r}") from error

    if faction_id <= 0:
        raise ValueError(f"faction must be positive, got {faction_id}")
    return faction_id


def parse_rate(value, faction_id, column):
    try:
        rate = Decimal(str(value))
    except (InvalidOperation, TypeError, ValueError) as error:
        raise ValueError(
            f"faction {faction_id} {column} must be numeric, got {value!r}"
        ) from error

    if not rate.is_finite() or rate < 0:
        raise ValueError(
            f"faction {faction_id} {column} must be a non-negative finite rate"
        )
    return rate


def format_rate(rate):
    formatted = format(rate, "f")
    if "." in formatted:
        formatted = formatted.rstrip("0").rstrip(".")
    return formatted or "0"


def load_reputation_rates(source_root):
    base_file = (
        source_root
        / "data"
        / "sql"
        / "base"
        / "db_world"
        / "reputation_reward_rate.sql"
    )
    if not base_file.is_file():
        raise ValueError(
            f"Could not find AzerothCore reputation_reward_rate at {base_file}"
        )

    raw_rows = load_acore_sql_table(
        source_root,
        "reputation_reward_rate",
        key_column="faction",
        include_modules=True,
    )
    if not raw_rows:
        raise ValueError(
            f"No AzerothCore reputation_reward_rate rows were loaded from {source_root}"
        )

    rates = {}
    for raw_faction_id, row in raw_rows.items():
        faction_id = parse_faction_id(raw_faction_id)

        parsed_rates = {
            column: parse_rate(row.get(column), faction_id, column)
            for column in ALL_RATE_COLUMNS
        }
        rates[faction_id] = tuple(
            parsed_rates[column] for column in QUEST_RATE_COLUMNS
        )

    return rates


def build_lua(rates):
    lines = [
        "--! This file is automatically generated. Do not modify.",
        "-- Generated by tools/generate_acore_reputation_rates.py from AzerothCore",
        "-- reputation_reward_rate base, update, and module SQL.",
        "",
        "-- factionId = {quest, daily, weekly, monthly, repeatable}",
        "QuestieCompat.AzerothCoreReputationRates = {",
    ]

    for faction_id in sorted(rates):
        formatted_rates = ", ".join(format_rate(rate) for rate in rates[faction_id])
        lines.append(f"    [{faction_id}] = {{{formatted_rates}}},")

    lines.extend(["}", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate AzerothCore faction-specific quest reputation rates."
    )
    parser.add_argument(
        "--acore-source",
        required=True,
        type=Path,
        help="Path to the AzerothCore source tree.",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        type=Path,
        help=f"Generated Lua output (default: {DEFAULT_OUTPUT}).",
    )
    args = parser.parse_args()

    rates = load_reputation_rates(args.acore_source)
    output = build_lua(rates)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")

    non_default_rows = sum(any(rate != 1 for rate in row) for row in rates.values())
    print(
        f"Wrote {args.output} with {len(rates)} faction rows "
        f"({non_default_rows} with non-default quest rates)."
    )


if __name__ == "__main__":
    main()
